Jenkins 60935 Code churn metric
jenkinsci/forensics-api-plugin pull request #216
Opened 2020-09-08 21:24 UTC by rathaya

2020-09-08 21:25 UTC, rathaya commented
Some names will be changed (LocChanges for example), as this is still a wip.

2020-09-09 14:01 UTC, rathaya commented on src/main/java/io/jenkins/plugins/forensics/miner/ForensicsBuildAction.java
> + * summary on the build page. The actual visualization of the results is defined in the matching {@code floatingBox.jelly}
Will revert the name change, was not intentional.

2020-09-14 22:08 UTC, uhafner requested changes
Can you please also check the new warnings? Otherwise Jenkins will not build the incremental release, see https://github.com/jenkinsci/forensics-api-plugin/pull/216/checks?check_run_id=1114576643 and Jenkins build.

2020-09-16 23:08 UTC, uhafner requested changes

2020-09-17 09:21 UTC, uhafner commented on src/main/java/io/jenkins/plugins/forensics/util/LocChanges.java
> +        return totalLoc;
wouldn't this be the same (then the field is not used)?
```suggestion
        return addedLines - removedLines;
```

2020-09-17 22:21 UTC, merged