Add test for `RelativeCountTrendChartTest`
jenkinsci/forensics-api-plugin pull request #355
Opened 2021-10-28 16:17 UTC by NikolasFunction

Added Test for class RelativeCountTrendChart.java
JENKINS-66866

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

2021-11-02 15:33 UTC, uhafner requested changes

2021-11-02 15:33 UTC, uhafner commented on src/test/java/io/jenkins/plugins/forensics/miner/RelativeCountTrendChartTest.java
> + *
```suggestion
```

2021-11-02 15:33 UTC, uhafner commented on src/test/java/io/jenkins/plugins/forensics/miner/RelativeCountTrendChartTest.java
> +
Use new lines only to structure code
```suggestion
```

2021-11-02 15:33 UTC, uhafner commented on src/test/java/io/jenkins/plugins/forensics/miner/RelativeCountTrendChartTest.java
> +
```suggestion
```

2021-11-02 15:33 UTC, uhafner commented on src/test/java/io/jenkins/plugins/forensics/miner/RelativeCountTrendChartTest.java
> +    private final RelativeCountTrendChart relativeCountTrendChart = new RelativeCountTrendChart();
No fields in unit tests, inline that into the method

2021-11-02 15:33 UTC, uhafner commented on src/test/java/io/jenkins/plugins/forensics/miner/RelativeCountTrendChartTest.java
> +        Iterable<BuildResult<CommitStatisticsBuildAction>> buildResult = createBuildResults(false);
Inline that call to make it readable:
```suggestion
        Iterable<BuildResult<CommitStatisticsBuildAction>> buildResult = new ArrayList<>();
```

2021-11-02 15:33 UTC, uhafner commented on src/test/java/io/jenkins/plugins/forensics/miner/RelativeCountTrendChartTest.java
> +        assertThat(linesChartModel.getSeries()).allSatisfy(series -> assertThat(series.getData()).hasSize(4));
Optional: if you want to make sure that the chart actually is correct, you can use JSON assertions, see review in https://github.com/jenkinsci/forensics-api-plugin/pull/351

2021-11-03 18:13 UTC, Fiesepille commented
Seems to be a bug that commit/build #73bcd5d failed.
Following build #404805e succeeded, allthough the code styling was the only change.

2021-11-03 18:22 UTC, uhafner commented
> Seems to be a bug that commit/build #73bcd5d failed.
> Following build #404805e succeeded, allthough the code styling was the only change.

I think the download of an artifact from the maven repository was broken but that should be fixed now.

2021-11-03 18:22 UTC, uhafner approved these changes

2021-11-03 18:23 UTC, merged