JENKINS-66863 Unit test for RelativeCountForensicsSeriesBuilder
jenkinsci/forensics-api-plugin pull request #453
Opened 2022-10-16 02:37 UTC by denis-arruda

Unit test for RelativeCountForensicsSeriesBuilder

2022-10-16 20:15 UTC, uhafner requested changes
Please also use IntelliJ auto-format to fix the formatting errors. 

Otherwise the PR looks good, thanks!

2022-10-16 20:15 UTC, uhafner commented on src/test/java/io/jenkins/plugins/forensics/miner/RelativeCountForensicsSeriesBuilderTest.java
> +        assertThat(countStatistics.get("authors")).isEqualTo(5);
It would make sense to use the constants defined in the `RelativeCountForensicsSeriesBuilder` .
```suggestion
        assertThat(countStatistics.get(AUTHORS)).isEqualTo(5);

```

2022-10-23 21:06 UTC, uhafner commented
@denis-arruda Are you planning to fix those small formatting problems?

2022-10-26 00:56 UTC, denis-arruda commented
Sorry for the delay. Created a new one.

2022-10-26 00:56 UTC, closed without merging