Case sensitivity on emails
jenkinsci/forensics-api-plugin pull request #467
Opened 2023-01-18 06:29 UTC by Jagrutiti

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

# Description

Updated code to fix case sensitivity issue of email ids.

# Jira id
https://issues.jenkins.io/browse/JENKINS-70239

2023-01-18 06:32 UTC, Jagrutiti commented on src/test/java/io/jenkins/plugins/forensics/miner/CommitStatisticsTest.java
> -                .hasAuthorCount(2)
Test cases were failing. I was not sure about my solution so did not make a lot of changes. 

If my fix makes sense I can start working on the test cases.

2023-01-18 07:46 UTC, uhafner commented on src/test/java/io/jenkins/plugins/forensics/miner/CommitStatisticsTest.java
> -                .hasAuthorCount(2)
Actually you have a compile error!

2023-01-18 07:51 UTC, uhafner requested changes
Best way to start an issue is:
*Create a failing test case that exposes the problem*

2023-01-18 07:51 UTC, uhafner commented on src/main/java/io/jenkins/plugins/forensics/miner/CommitStatistics.java
> +        return (int) commits.stream().map(p -> equalsIgnoreCase(property)).distinct().count();
This will not work. You need something like:
```suggestion
        return (int) commits.stream().map(property).map(s -> String.toLowerCase(Locale.ENGLISH)).distinct().count();
```

Then the existing test should succeed.

2023-01-18 11:28 UTC, Jagrutiti commented on src/main/java/io/jenkins/plugins/forensics/miner/CommitStatistics.java
> -        return (int) commits.stream().map(property).map(s -> String.toLowerCase(Locale.ENGLISH)).distinct().count();
Intellij threw the following error for this syntax:

```
Non-static method 'toLowerCase(java.util.Locale)' cannot be referenced from a static context
```

I changed it to the current one. And updated the test cases. Shall I write new one for this change?

2023-01-18 11:30 UTC, Jagrutiti commented
> Create a failing test case that exposes the problem

Do you want me to create this test case?

2023-01-18 12:39 UTC, uhafner requested changes

2023-01-18 12:39 UTC, uhafner commented on src/main/java/io/jenkins/plugins/forensics/miner/CommitStatistics.java
> -        return (int) commits.stream().map(property).map(s -> String.toLowerCase(Locale.ENGLISH)).distinct().count();
You should write a failing test before you touch the code 🥲.

2023-01-18 12:39 UTC, uhafner commented on src/main/java/io/jenkins/plugins/forensics/miner/CommitStatistics.java
> +        return (int) commits.stream().map(property).map(s -> property.toString().toLowerCase()).distinct().count();
This is wrong, and that the reason you needed to change the existing tests 🙈 

You are counting the number of different properties now! But you need to count the values!!!

```suggestion
        return (int) commits.stream().map(property).map(s -> s.toLowerCase(Locale.ENGLISH)).distinct().count();
```

And do not forget to add the import for Locale? Are you not coding in an IDE?

2023-01-18 14:37 UTC, uhafner commented
> > Create a failing test case that exposes the problem
> 
> Do you want me to create this test case?

Yes

2023-01-18 15:03 UTC, Jagrutiti commented on src/main/java/io/jenkins/plugins/forensics/miner/CommitStatistics.java
> +        return (int) commits.stream().map(property).map(s -> property.toString().toLowerCase()).distinct().count();
> This is wrong, and that the reason you needed to change the existing tests 🙈
> 
> You are counting the number of different properties now! But you need to count the values!!!
> 
> And do not forget to add the import for Locale. Are you not coding in an IDE?

I am sorry for the writing the wrong code. I do not know how to write test cases in Java. I want to learn. The documentation does not match anything. Jenkins code gets complex at times.

If your schedule allows would you be my mentor? For a few weeks, say 3-4 weeks, or whatever fits your schedule. I promise I would not waste your time. 

I can research and learn on my own. I need help in understanding which part of code does what and in writing test cases.

2023-01-18 15:07 UTC, uhafner commented on src/main/java/io/jenkins/plugins/forensics/miner/CommitStatistics.java
> +        return (int) commits.stream().map(property).map(s -> property.toString().toLowerCase()).distinct().count();
I can guide you for *this* specific issue and associated test. For additional things I have no time right now.

2023-01-18 15:08 UTC, Jagrutiti commented on src/main/java/io/jenkins/plugins/forensics/miner/CommitStatistics.java
> +        return (int) commits.stream().map(property).map(s -> property.toString().toLowerCase()).distinct().count();
> I can guide you for _this_ specific issue and associated test. For additional things I have no time right now.

Thank you for guiding me for this issue.

2023-01-18 15:08 UTC, Jagrutiti commented on src/main/java/io/jenkins/plugins/forensics/miner/CommitStatistics.java
> +        return (int) commits.stream().map(property).map(s -> property.toString().toLowerCase()).distinct().count();
I will start with the test case first.

2023-01-19 07:46 UTC, Jagrutiti commented on src/main/java/io/jenkins/plugins/forensics/miner/CommitStatistics.java
> +        return (int) commits.stream().map(property).map(s -> property.toString().toLowerCase()).distinct().count();
Hey @uhafner 

I wrote the test case. Reverted all the old changes and fixed the the code to resolve the issue.

2023-01-19 12:56 UTC, uhafner requested changes

2023-01-19 12:56 UTC, uhafner commented on .idea/.gitignore
> +/workspace.xml
Remove the unrelated files below `.idea` from the PR. (I need to change the Git ignore file to ignore .idea folder).

2023-01-19 12:56 UTC, uhafner commented on src/test/java/io/jenkins/plugins/forensics/miner/CommitStatisticsTest.java
> +    void checkEmailIdCount(){
```suggestion
    void shouldIgnoreCapitalizationOfEmailNames() {
```

2023-01-19 12:56 UTC, uhafner commented on src/test/java/io/jenkins/plugins/forensics/miner/CommitStatisticsTest.java
> +        assertThat(firstCommit).hasAuthorCount(1);
This code should be moved to Line 156 right after the first commit. Then we have just a single entry in commits.

2023-01-19 14:31 UTC, uhafner approved these changes

2023-01-19 14:42 UTC, merged